<?php
require_once 'config/database.php';
$results=[]; $errors=[];
$queries=[
'users'=>"CREATE TABLE IF NOT EXISTS `users` (`id` INT AUTO_INCREMENT PRIMARY KEY,`username` VARCHAR(50) UNIQUE NOT NULL,`email` VARCHAR(100) UNIQUE NOT NULL,`password` VARCHAR(255) NOT NULL,`avatar` VARCHAR(255) DEFAULT NULL,`bio` VARCHAR(255) DEFAULT NULL,`status` ENUM('online','offline','busy','away') DEFAULT 'offline',`last_seen` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,`peer_id` VARCHAR(100) DEFAULT NULL,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB",
'friendships'=>"CREATE TABLE IF NOT EXISTS `friendships` (`id` INT AUTO_INCREMENT PRIMARY KEY,`requester_id` INT NOT NULL,`receiver_id` INT NOT NULL,`status` ENUM('pending','accepted','rejected') DEFAULT 'pending',`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (`requester_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,FOREIGN KEY (`receiver_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,UNIQUE KEY `uf` (`requester_id`,`receiver_id`)) ENGINE=InnoDB",
'messages'=>"CREATE TABLE IF NOT EXISTS `messages` (`id` INT AUTO_INCREMENT PRIMARY KEY,`sender_id` INT NOT NULL,`receiver_id` INT NOT NULL,`content` TEXT NOT NULL,`type` ENUM('text','system') DEFAULT 'text',`is_read` TINYINT(1) DEFAULT 0,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (`sender_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,FOREIGN KEY (`receiver_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB",
'call_signals'=>"CREATE TABLE IF NOT EXISTS `call_signals` (`id` INT AUTO_INCREMENT PRIMARY KEY,`caller_id` INT NOT NULL,`receiver_id` INT NOT NULL,`caller_peer_id` VARCHAR(100) NOT NULL,`status` ENUM('calling','active','ended','rejected') DEFAULT 'calling',`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY (`caller_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,FOREIGN KEY (`receiver_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB",
'servers'=>"CREATE TABLE IF NOT EXISTS `servers` (`id` INT AUTO_INCREMENT PRIMARY KEY,`name` VARCHAR(100) NOT NULL,`icon` VARCHAR(255) DEFAULT NULL,`owner_id` INT NOT NULL,`invite_code` VARCHAR(20) UNIQUE NOT NULL,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (`owner_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB",
'server_members'=>"CREATE TABLE IF NOT EXISTS `server_members` (`id` INT AUTO_INCREMENT PRIMARY KEY,`server_id` INT NOT NULL,`user_id` INT NOT NULL,`role` ENUM('owner','admin','member') DEFAULT 'member',`joined_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (`server_id`) REFERENCES `servers`(`id`) ON DELETE CASCADE,FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,UNIQUE KEY `usm` (`server_id`,`user_id`)) ENGINE=InnoDB",
'channels'=>"CREATE TABLE IF NOT EXISTS `channels` (`id` INT AUTO_INCREMENT PRIMARY KEY,`server_id` INT NOT NULL,`name` VARCHAR(100) NOT NULL,`type` ENUM('text','voice') DEFAULT 'text',`position` INT DEFAULT 0,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (`server_id`) REFERENCES `servers`(`id`) ON DELETE CASCADE) ENGINE=InnoDB",
'channel_messages'=>"CREATE TABLE IF NOT EXISTS `channel_messages` (`id` INT AUTO_INCREMENT PRIMARY KEY,`channel_id` INT NOT NULL,`sender_id` INT NOT NULL,`content` TEXT NOT NULL,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON DELETE CASCADE,FOREIGN KEY (`sender_id`) REFERENCES `users`(`id`) ON DELETE CASCADE) ENGINE=InnoDB",
'voice_participants'=>"CREATE TABLE IF NOT EXISTS `voice_participants` (`id` INT AUTO_INCREMENT PRIMARY KEY,`channel_id` INT NOT NULL,`user_id` INT NOT NULL,`peer_id` VARCHAR(100) NOT NULL,`joined_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON DELETE CASCADE,FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,UNIQUE KEY `uvp` (`channel_id`,`user_id`)) ENGINE=InnoDB",
];
foreach($queries as $name=>$sql){try{$pdo->exec($sql);$results[]="✅ $name";}catch(PDOException $e){$errors[]="❌ $name: ".$e->getMessage();}}
?><!DOCTYPE html><html><head><meta charset="UTF-8"><title>KaiVC Setup</title>
<style>*{font-family:monospace;box-sizing:border-box;}body{background:#03080f;color:#e2e8f0;padding:40px 20px;max-width:560px;margin:0 auto;}h1{color:#4a9eff;margin-bottom:20px;}
.ok{background:rgba(34,197,94,.1);border:1px solid rgba(34,197,94,.3);color:#4ade80;padding:10px 14px;border-radius:8px;margin-bottom:8px;}
.err{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.3);color:#f87171;padding:10px 14px;border-radius:8px;margin-bottom:8px;}
.btn{display:inline-block;margin-top:20px;background:linear-gradient(135deg,#1d4ed8,#4a9eff);color:#fff;padding:12px 24px;border-radius:100px;text-decoration:none;font-weight:bold;font-family:sans-serif;}</style>
</head><body><h1>⚙️ KaiVC Setup</h1>
<?php foreach($results as $r):?><div class="ok"><?=$r?></div><?php endforeach;?>
<?php foreach($errors as $e):?><div class="err"><?=htmlspecialchars($e)?></div><?php endforeach;?>
<?php if(empty($errors)):?><a href="login.php" class="btn">🚀 Buka KaiVC</a><?php endif;?>
</body></html>
